<a href="https://colab.research.google.com/github/zenyonki/telecom_x_project/blob/main/Telecom_X_MC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto Telecom X para Alura LATAM

## Importaci√≥n de bibliotecas

In [17]:
import requests
import pandas as pd

url = "https://raw.githubusercontent.com/sthemonica/alura-voz/refs/heads/main/Dados/Telco-Customer-Churn.json"

response = requests.get(url)
data = response.json()

df = pd.DataFrame(data)

df

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
...,...,...,...,...,...,...
7262,9987-LUTYD,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
7263,9992-RRAMN,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7264,9992-UJOEL,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
7265,9993-LHIEB,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."
7266,9995-HOTOH,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'No', 'MultipleLines': 'No ph...","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Two year', 'PaperlessBilling': '..."

In [22]:
#Normalizamos, es decir, se hace un df con columnas donde antes hab√≠a diccionarios
df_normalizado = pd.json_normalize(data)
df_normalizado

,customerID,Churn,customer.gender,customer.SeniorCitizen,customer.Partner,customer.Dependents,customer.tenure,phone.PhoneService,phone.MultipleLines,internet.InternetService,...,internet.OnlineBackup,internet.DeviceProtection,internet.TechSupport,internet.StreamingTV,internet.StreamingMovies,account.Contract,account.PaperlessBilling,account.PaymentMethod,account.Charges.Monthly,account.Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.60,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.90,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.90,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.00,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.90,267.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7262,9987-LUTYD,No,Female,0,No,No,13,Yes,No,DSL,...,No,No,Yes,No,No,One year,No,Mailed check,55.15,742.9
7263,9992-RRAMN,Yes,Male,0,Yes,No,22,Yes,Yes,Fiber optic,...,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,85.10,1873.7
7264,9992-UJOEL,No,Male,0,No,No,2,Yes,No,DSL,...,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,50.30,92.75
7265,9993-LHIEB,No,Male,0,Yes,Yes,67,Yes,No,DSL,...,No,Yes,Yes,No,Yes,Two year,No,Mailed check,67.85,4627.65
7266,9995-HOTOH,No,Male,0,Yes,Yes,63,No,No phone service,DSL,...,Yes,Yes,No,Yes,Yes,Two year,No,Electronic check,59.00,3707.6

In [23]:
df_normalizado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerID                 7267 non-null   object
 1   Churn                      7267 non-null   object
 2   customer.gender            7267 non-null   object
 3   customer.SeniorCitizen     7267 non-null   int64
 4   customer.Partner           7267 non-null   object
 5   customer.Dependents        7267 non-null   object
 6   customer.tenure            7267 non-null   int64
 7   phone.PhoneService         7267 non-null   object
 8   phone.MultipleLines        7267 non-null   object
 9   internet.InternetService   7267 non-null   object
 10  internet.OnlineSecurity    7267 non-null   object
 11  internet.OnlineBackup      7267 non-null   object
 12  internet.DeviceProtection  7267 non-null   object
 13  internet.TechSupport       7267 non-null   object
 14  internet.StreamingTV       7267 non-null   object
 15  internet.StreamingMovies   7267 non-null   object
 16  account.Contract           7267 non-null   object
 17  account.PaperlessBilling   7267 non-null   object
 18  account.PaymentMethod      7267 non-null   object
 19  account.Charges.Monthly    7267 non-null   float64
 20  account.Charges.Total      7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

In [29]:
#Se guarda el DF normalizado para reusarlo en otro momento.
df_normalizado.to_csv('df_normalizado.csv', index=False)

In [31]:
# Verifique si hay valores √∫nicos en cada columna
for col in df_normalizado.columns:
  print(f"valores √∫nicos en la columna'{col}': {df_normalizado[col].nunique()}")
  if df_normalizado[col].nunique() < 50: # Imprima los valores solamente si no hay muchos
    print(df_normalizado[col].unique())
    print('-' * 50)  # L√≠nea divisoria para mejor visualizaci√≥n

valores √∫nicos en la columna'customerID': 7267
valores √∫nicos en la columna'Churn': 3
['No' 'Yes' '']
--------------------------------------------------
valores √∫nicos en la columna'customer.gender': 2
['Female' 'Male']
--------------------------------------------------
valores √∫nicos en la columna'customer.SeniorCitizen': 2
[0 1]
--------------------------------------------------
valores √∫nicos en la columna'customer.Partner': 2
['Yes' 'No']
--------------------------------------------------
valores √∫nicos en la columna'customer.Dependents': 2
['Yes' 'No']
--------------------------------------------------
valores √∫nicos en la columna'customer.tenure': 73
valores √∫nicos en la columna'phone.PhoneService': 2
['Yes' 'No']
--------------------------------------------------
valores √∫nicos en la columna'phone.MultipleLines': 3
['No' 'Yes' 'No phone service']
--------------------------------------------------
valores √∫nicos en la columna'internet.InternetService': 3
['DSL' 'Fiber optic' 'No']
--------------------------------------------------
valores √∫nicos en la columna'internet.OnlineSecurity': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'internet.OnlineBackup': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'internet.DeviceProtection': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'internet.TechSupport': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'internet.StreamingTV': 3
['Yes' 'No' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'internet.StreamingMovies': 3
['No' 'Yes' 'No internet service']
--------------------------------------------------
valores √∫nicos en la columna'account.Contract': 3
['One year' 'Month-to-month' 'Two year']
--------------------------------------------------
valores √∫nicos en la columna'account.PaperlessBilling': 2
['Yes' 'No']
--------------------------------------------------
valores √∫nicos en la columna'account.PaymentMethod': 4
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
--------------------------------------------------
valores √∫nicos en la columna'account.Charges.Monthly': 1585
valores √∫nicos en la columna'account.Charges.Total': 6531

In [37]:
#Duplicados
print("Numero de duplicados", df_normalizado.duplicated().sum())

Numero de duplicados 0

In [36]:
# Nulos
print("Numero de Nulos", df_normalizado.isnull().sum())

Numero de Nulos customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [35]:
df_normalizado.apply(lambda x: x.astype(str).str.strip() == '').sum()

customerID                     0
Churn                        224
customer.gender                0
customer.SeniorCitizen         0
customer.Partner               0
customer.Dependents            0
customer.tenure                0
phone.PhoneService             0
phone.MultipleLines            0
internet.InternetService       0
internet.OnlineSecurity        0
internet.OnlineBackup          0
internet.DeviceProtection      0
internet.TechSupport           0
internet.StreamingTV           0
internet.StreamingMovies       0
account.Contract               0
account.PaperlessBilling       0
account.PaymentMethod          0
account.Charges.Monthly        0
account.Charges.Total         11
dtype: int64

In [39]:
df_normalizado['account.Charges.Total'] = pd.to_numeric(df_normalizado['account.Charges.Total'], errors='coerce')
df_normalizado['account.Charges.Total'].dtype

dtype('float64')

In [41]:
# Se eliminan filas vac√≠as, deben de ser: 224

df_normalizado = df_normalizado[df_normalizado['Churn'].str.strip() != '']
print("N√∫mero de filas despu√©s de eliminar las vac√≠as en 'Churn':", len(df_normalizado))

N√∫mero de filas despu√©s de eliminar las vac√≠as en 'Churn': 7043

In [42]:
df_normalizado.apply(lambda x: x.astype(str).str.strip() == '').sum()

customerID                   0
Churn                        0
customer.gender              0
customer.SeniorCitizen       0
customer.Partner             0
customer.Dependents          0
customer.tenure              0
phone.PhoneService           0
phone.MultipleLines          0
internet.InternetService     0
internet.OnlineSecurity      0
internet.OnlineBackup        0
internet.DeviceProtection    0
internet.TechSupport         0
internet.StreamingTV         0
internet.StreamingMovies     0
account.Contract             0
account.PaperlessBilling     0
account.PaymentMethod        0
account.Charges.Monthly      0
account.Charges.Total        0
dtype: int64

In [43]:
df_normalizado.describe()

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total
count,7043.000000,7043.000000,7043.000000,7032.000000
mean,0.162147,32.371149,64.761692,2283.300441
std,0.368612,24.559481,30.090047,2266.771362
min,0.000000,0.000000,18.250000,18.800000
25%,0.000000,9.000000,35.500000,401.450000
50%,0.000000,29.000000,70.350000,1397.475000
75%,0.000000,55.000000,89.850000,3794.737500
max,1.000000,72.000000,118.750000,8684.800000

In [44]:
df_normalizado['account.Charges.Daily'] = df_normalizado['account.Charges.Monthly'] / 30
df_normalizado['account.Charges.Daily']

0       2.186667
1       1.996667
2       2.463333
3       3.266667
4       2.796667
          ...
7262    1.838333
7263    2.836667
7264    1.676667
7265    2.261667
7266    1.966667
Name: account.Charges.Daily, Length: 7043, dtype: float64

In [46]:
df_normalizado = df_normalizado.drop('account.Charges.Daily', errors='ignore')

In [48]:
df_normalizado.describe()

,customer.SeniorCitizen,customer.tenure,account.Charges.Monthly,account.Charges.Total,account.Charges.Daily
count,7043.000000,7043.000000,7043.000000,7032.000000,7043.000000
mean,0.162147,32.371149,64.761692,2283.300441,2.158723
std,0.368612,24.559481,30.090047,2266.771362,1.003002
min,0.000000,0.000000,18.250000,18.800000,0.608333
25%,0.000000,9.000000,35.500000,401.450000,1.183333
50%,0.000000,29.000000,70.350000,1397.475000,2.345000
75%,0.000000,55.000000,89.850000,3794.737500,2.995000
max,1.000000,72.000000,118.750000,8684.800000,3.958333

In [50]:
#Df normalizado ya con la nueva columna de Cargos diarios
df_normalizado.to_csv('df_normalizado_chares_daily.csv', index=False)